import logging

import numpy as np
from app.models.transcript_segment import TranscriptSegment


logger = logging.getLogger(__name__)


def cosine_similarity(
    embedding_a: list[float],
    embedding_b: list[float],
) -> float:
    """
    Calculate cosine similarity between two embeddings.

    Embeddings generated by our embedding service are already
    normalized, so cosine similarity is simply their dot product.
    """

    if not embedding_a or not embedding_b:
        return 0.0

    a = np.asarray(
        embedding_a,
        dtype=np.float32,
    )

    b = np.asarray(
        embedding_b,
        dtype=np.float32,
    )

    similarity = float(
        np.dot(a, b)
    )

    return similarity


def calculate_semantic_coherence(
    segments: list[TranscriptSegment],
) -> float:
    """
    Calculate how semantically coherent a group of transcript
    segments is.

    Compares neighboring transcript segments.

    Returns:
        Score between 0.0 and 1.0.
    """

    embeddings = [
        segment.embedding
        for segment in segments
        if segment.embedding is not None
    ]

    if len(embeddings) < 2:
        return 0.0

    similarities = []

    for current, next_embedding in zip(
        embeddings,
        embeddings[1:],
    ):
        similarity = cosine_similarity(
            current,
            next_embedding,
        )

        similarities.append(
            similarity
        )

    if not similarities:
        return 0.0

    average_similarity = sum(
        similarities
    ) / len(similarities)

    # Convert approximately from [-1, 1]
    # to [0, 1].
    score = (
        average_similarity + 1.0
    ) / 2.0

    score = max(
        0.0,
        min(score, 1.0),
    )

    logger.debug(
        "Calculated semantic coherence: "
        "segments=%s score=%.3f",
        len(segments),
        score,
    )

    return score