"""add audio  path

Revision ID: 043c55012f50
Revises: 5f43ae754992
Create Date: 2026-08-30 23:46:48.727840

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '043c55012f50'
down_revision: Union[str, Sequence[str], None] = '5f43ae754992'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('audio_path', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'audio_path')
    # ### end Alembic commands ###
