"""add embedding to transcript segments

Revision ID: 1ecfbc0d6bb2
Revises: e044f6782341
Create Date: 2026-08-31 22:55:32.998697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '1ecfbc0d6bb2'
down_revision: Union[str, Sequence[str], None] = 'e044f6782341'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transcript_segments', sa.Column('embedding', Vector(dim=384), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transcript_segments', 'embedding')
    # ### end Alembic commands ###
