"""make youtube id unique

Revision ID: 80dbb48a43e5
Revises: 1ecfbc0d6bb2
Create Date: 2026-09-06 16:54:41.582691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80dbb48a43e5'
down_revision: Union[str, Sequence[str], None] = '1ecfbc0d6bb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('videos_youtube_id_key'), 'videos', type_='unique')
    op.create_index(op.f('ix_videos_youtube_id'), 'videos', ['youtube_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_videos_youtube_id'), table_name='videos')
    op.create_unique_constraint(op.f('videos_youtube_id_key'), 'videos', ['youtube_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
