"""update processing jobs

Revision ID: 9b51ff53f89d
Revises: 6a5ef23e9a04
Create Date: 2026-08-30 22:41:11.672808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9b51ff53f89d'
down_revision: Union[str, Sequence[str], None] = '6a5ef23e9a04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_processing_jobs_video_id'), 'processing_jobs', ['video_id'], unique=False)
    op.drop_constraint(op.f('processing_jobs_video_id_fkey'), 'processing_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'processing_jobs', 'videos', ['video_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'processing_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('processing_jobs_video_id_fkey'), 'processing_jobs', 'videos', ['video_id'], ['id'])
    op.drop_index(op.f('ix_processing_jobs_video_id'), table_name='processing_jobs')
    # ### end Alembic commands ###
