"""add clips

Revision ID: e044f6782341
Revises: 0d1b3f3e3bb2
Create Date: 2026-08-31 08:43:46.477002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e044f6782341'
down_revision: Union[str, Sequence[str], None] = '0d1b3f3e3bb2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clips',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.Integer(), nullable=False),
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.Float(), nullable=False),
    sa.Column('end_time', sa.Float(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('duration', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['candidate_id'], ['clip_candidates.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_clips_candidate_id'), 'clips', ['candidate_id'], unique=False)
    op.create_index(op.f('ix_clips_video_id'), 'clips', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clips_video_id'), table_name='clips')
    op.drop_index(op.f('ix_clips_candidate_id'), table_name='clips')
    op.drop_table('clips')
    # ### end Alembic commands ###
